name = "AWSBatch"
uuid = "dcae83d4-2881-5875-9d49-e5534165e9c0"
license = "MIT"
authors = ["Invenia Technical Computing"]
version = "2.0.0"

[deps]
AWS = "fbe9abb3-538b-5e4e-ba9e-bc94f4f92ebc"
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
Mocking = "78c3b35d-d492-501b-9361-3d52fe80e533"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
AWS = "1"
AutoHashEquals = "0.2.0"
Memento = "0.7, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13, 1"
Mocking = "0.7"
OrderedCollections = "1.4"
julia = "1"

[extras]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["HTTP", "Test"]
